### ISSUE TITLE
I have an error that can't even let me run "hugo server"

### ISSUE THREAD

**Issue by cindrmon** [rmsubekti/the-roots-home#2]
```
Error: Error building site: TOCSS: failed to transform "css/main.scss" (text/x-scss): resource "scss/main.scss_e86386c8bae1cd02295de71a1be078d6" not found in file cache
```

This is the error that pops up whenever i start a `hugo server` instance. Am I doing something wrong?

**Comment by bect** [comment]
not really, 
but mine is ok, even if I delete the cache.
maybe you should use the extended hugo version.
or if you want to keep using the basic hugo version, you may need to copy the `resources` folder from  [exampleSite](https://github.com/rmsubekti/the-roots-home/tree/master/exampleSite) of this theme.
and then put that folder in the root of your site folder.

**Comment by plum** [comment]
That is an error I've had on Hugo sites that require postcss to be installed. 
BTW: I love the layout here. Beleive I may adopt it. Suspect it may be a better user experience for reading documents in a section. I also like it to wrok with a blog, am going see ho wit may work for that too....

**Comment by bect** [comment]
@plum  yup, that's why i only use hugo pipe 'toCSS'. 
that's what I'm thinking, like storing portfolio, presentation and all kind of that stuff in a different folder, which can't do that for now, because Hugo just serves content as a page, it may need to hardcoded the template to make it work.
and why not, I don't really know what is the name of the layout, adopt it from this website's layout `http://mirror.poliwangi.ac.id/blankon/` and add some glitter it so it looks a bit prettier.

**Comment by plum** [comment]
Yes. That's a good point, concerning portfolo etc and the seperate folder.
